apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "compiler.fullname" . }}-config
  labels:
    {{- include "compiler.labels" . | nindent 4 }}
data:
  application.yml: |-
    springdoc:
      swagger-ui:
        path: "/swagger-ui.html"
      api-docs:
        path: "/api-docs"
      show-actuator: true
    management:
      endpoint:
        health:
          show-details: always
        env:
          keys-to-sanitize: password, key, secret, token
        service-registry:
          enabled: false
      metrics:
        export:
          prometheus:
            enabled: true
      endpoints:
        web:
          exposure:
            include: health, info, metrics, prometheus, beans, logfile
          base-path: /
    env:
      execution:
        path-separator: "/"
        input-file-name: "input"
        expected-output-file-name: "output"
        input-output-file-extension: ".txt"
        delete-source-code: false
        host-mounted-path: "/compiler/executions"
        container-mounted-path: "/app"
        volume: "/compiler/executions"
