apiVersion: v1
kind: Service
metadata:
  name: {{ include "compiler.fullname" . }}
  labels:
    {{- include "compiler.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: compiler
  selector:
    {{- include "compiler.selectorLabels" . | nindent 4 }}
