apiVersion: v1
kind: Service
metadata:
  name: {{ include "couchbase.fullname" . }}
  labels:
    {{- include "couchbase.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: cb-8091
      port: 8091
      targetPort: 8091
    - name: cb-8092
      port: 8092
      targetPort: 8092
    - name: cb-8093
      port: 8093
      targetPort: 8093
    - name: cb-8094
      port: 8094
      targetPort: 8094
    - name: cb-11210
      port: 11210
      targetPort: 11210
  selector:
    {{- include "couchbase.selectorLabels" . | nindent 4 }}
