apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "problem-api.fullname" . }}-config
  labels:
    {{- include "problem-api.labels" . | nindent 4 }}
data:
  application.yml: |-
    springdoc:
      swagger-ui:
        path: "/swagger-ui.html"
      api-docs:
        path: "/api-docs"
    management:
      endpoint:
        health:
          show-details: always
        env:
          keys-to-sanitize: password, key, secret, token
        service-registry:
          enabled: false
      metrics:
        export:
          prometheus:
            enabled: true
      endpoints:
        web:
          exposure:
            include: health, info, metrics, prometheus, beans, logfile
          base-path: /
    
    logging:
      level:
        org:
          springframework:
            data:
              couchbase:
                repository:
                  query: DEBUG
    spring:
      application:
        name: problem-api